main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.activity, name='activity'),
    path('delete/<str:pk>', views.delete, name='activityDelete'),
    path('delete/member/<str:pk>', views.deleteMember, name='memberDelete')

]

story6fikri/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7/', include('story7fikri.urls')),
    path('story8/', include('story8fikri.urls')),
    path('story9/', include('story9fikri.urls')),
]

story7fikri/urls.py
from django.urls import path

from . import views

app_name = 'story7fikri'

urlpatterns = [
    path('', views.home, name='home'),
]

story8fikri/urls.py
from django.urls import path

from . import views

app_name = 'story8fikri'

urlpatterns = [
    path('', views.book, name='book'),
    path('volumes/', views.search, name='search')
]

story9fikri/urls.py
from django.urls import path
from . import views

app_name = 'story9fikri'

urlpatterns = [
    path('SignIn/', views.SignIn, name='SignIn'),
    path('SignOut/', views.SignOut, name='SignOut')
]

main/models.py
from django.db import models

# Create your models here.


class Activity(models.Model):
    activity = models.CharField(max_length=100)
    def __str__(self):
        return self.activity

class Member(models.Model):
    member = models.CharField(max_length=100)
    aktivitas = models.ForeignKey(Activity, on_delete=models.CASCADE)
    def __str__(self):
        return self.member

story7fikri/models.py
from django.db import models

# Create your models here.

story8fikri/models.py
from django.db import models

# Create your models here.

story9fikri/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from .models import Activity, Member

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'activity' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Activity"}),
        }

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'
        widgets = {
            'member' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Your Name"}),
        }

main/views.py
from django.shortcuts import render,redirect
from .models import Member, Activity
from .forms import MemberForm ,ActivityForm
from django.contrib import messages
# Create your views here.
def activity(request):
    if request.method == "POST":
        formA = ActivityForm(request.POST)
        formB = MemberForm(request.POST)
        if formA.is_valid():
            formA.save()
            messages.success(request, (f"Kegiatan {request.POST['activity']} berhasil ditambahkan!"))
            return redirect('main:activity')
        elif formB.is_valid():
            formB.save()
            messages.success(request, (f"{request.POST['member']} berhasil bergabung!"))
            return redirect('main:activity')
        else:
            messages.warning(request, (f"Input tidak sesuai!"))
            return redirect('main:activity')
    else:
        formA = ActivityForm()
        formB = MemberForm()
        activities = Activity.objects.all()
        members = Member.objects.all()
        context = {
            'formA' : formA,
            'formB' : formB,
            'activities' : activities,
            'members' : members
        }
        return render(request, 'main/index.html', context)

def delete(request,pk):
    activity = Activity.objects.get(id=pk)
    activity.delete()
    messages.warning(request, (f"Kegiatan {activity} berhasil dihapus!"))
    return redirect('main:activity')

def deleteMember(request,pk):
    member = Member.objects.get(id=pk)
    member.delete()
    messages.warning(request, (f"{member} berhasil dihapus!"))
    return redirect('main:activity')

story7fikri/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'story7.html')

story8fikri/views.py
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render
import json
import requests

# Create your views here.

def book(request):
    return render(request, 'story8.html')

def search(request):
    url = 'https://www.googleapis.com/books/v1/volumes'
    url +=  f"?maxResults={10}&q={request.GET.get('q')}"
    data = requests.get(url).json()
    return JsonResponse(data, json_dumps_params={'indent': 2})

story9fikri/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login as auth_SignIn, logout as auth_SignOut

def SignIn(request):
    if request.user.is_authenticated:
        return redirect('story8fikri:book')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_SignIn(request, user)
                request.session['username'] = user.first_name
                return redirect('story8fikri:book')
            else:
                return render(request, 'signup.html', {
                        'error' : 'invalid username or password'
                    }
                )
    return render(request, 'signup.html')

def SignOut(request):
    auth_SignOut(request)
    return redirect('story8fikri:book')

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>FIKRI</title>
    <nav class="nav">
      <div class="navbar-brand">Achmad Fikri Adidharma</div>
      <a class="nav-link"  href="{% url 'story7fikri:home' %}">story7</a>
    </nav>

</head>
<body style="background-color: #EDF2F4;">
    {% block content%}
    
    {% endblock content%}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/ok.js' %}"></script>
  </body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<head>
    {% block meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile Fikri</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    {% endblock meta %}
  </head>


{% block content %}
<body>
<div id="awal" style="background-color: #9fd7d1;height:100% ">
    <div class="container-fluid">    
    <h1 class="display-4 text-center pb-4 border-bottom" style:margin-top:60px></h1>
    <Form method="POST" class="row my-5">
        {% csrf_token %}
        <div class="col-7 ml-auto">
            {{ formA.activity }}
        </div>
        <button type="submit" class="btn btn-dark col-2 mr-auto">Add Activity</button>
    </Form>
    <hr>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="d-flex justify-content-around flex-wrap pb-4">
        {% for activity in activities %}
        <div class="card bg-light mt-5" style="width: 18rem;">
            <div class="card-header">
                <div class="row">
                    <h5 class="col-10 mb-2">{{ activity }}</h5>
                    <a href="{% url 'main:activityDelete' activity.id %}" class="col-2">
                        <button type="button" class="close mb-2">&times;</button>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <h6 class="card-title">Members:</h6>
                <p></p>
                <ul>
                    
                    {% for member in members %}
                    {% if member.aktivitas.id == activity.id %}
                    <li class="row">
                        <h5 class="col-10">{{ member }}</h5>
                        <a href="{% url 'main:memberDelete' member.id %}" class="col-2">
                            <button type="button" class="close">&times;</button>
                        </a>    
                    </li>
                    {% endif %}
                    {% endfor %}

                </ul>
                <form method="POST">
                    {% csrf_token %}
                    {{ formB.member }}
                    <input name="aktivitas" type="text" value="{{ activity.id }}" style="display: none;">
                    <button type="submit" class="btn btn-dark col-6 mt-2">Join</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    </div>
</div>
</div>
</body>
{% endblock content %}

story7fikri/templates/story7.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 7 Fikri</title>
{% endblock meta %}
{% block content %}

<div class="container" id="container">
  <div class="row" id="judul">
    <h1>Halo,<br>
        Hi! It's Achmad Fikri Adidharma, Sophomore at University of Indonesia.<br>Ready to get to know me more?
  </div>
  <div id="accordion">
    <div class="group" data-sort="0">
      <div id="head">
        <p> My Profile
          <button class="sort-up"><img src="{% static 'img/chevron-up.svg' %}"></button> 
          <button class="sort-down"><img src="{% static 'img/chevron-down.svg' %}"></button>
        </p>
      </div>
      <div id="content">
        <p>
            I am a highly motivated sophomore computer science student. I'm excited to learn new things not only limited to my major in
            computer science. I am currently interested to data analytics and business consulting. Hence, I decide to join business club and took
            some online courses related to piqued my curiousity. I'm a forever learner and I eager and enjoy to do things on my job.
        </p>
      </div>
    </div>

    <div class="group" data-sort="1">
      <div id="head">
        <p> Experience
          <button class="sort-up"><img src="{% static 'img/chevron-up.svg' %}"></button> 
          <button class="sort-down"><img src="{% static 'img/chevron-down.svg' %}"></button>
        </p>
      </div>
      <div id="content">
        <p>
            <b>Staff of Bazaar</b><br> PERAK FASILKOM UI<br><b>Member of Business Intelligence SIG</b><br>SISTEM FASILKOM UI<br><b>Staff of Event</b><br> PMB FASILKOM UI
        </p>
      </div>
    </div>

    <div class="group" data-sort="2">
      <div id="head">
        <p> Education
          <button class="sort-up"><img src="{% static 'img/chevron-up.svg' %}"></button> 
          <button class="sort-down"><img src="{% static 'img/chevron-down.svg' %}"></button>
        <p>
      </div>
      <div id="content">
        <p>
            SMPN 3 Jember<br>SMAN 1 Jember<br>S1 Ilmu Komputer Universitas Indonesia
        </p>
      </div>
    </div>

    <div class="group" data-sort="3">
      <div id="head">
        <p> Contact Me At
          <button class="sort-up"><img src="{% static 'img/chevron-up.svg' %}"></button> 
          <button class="sort-down"><img src="{% static 'img/chevron-down.svg' %}"></button>
        <p>
      </div>
      <div id="content">
        <p>
            Instagram : @fikriadidharma<br>LinkedIn : achmad fikri adidharma<br>Email : achmad.fikri91@ui.ac.id
        </p>
        
    </div>

  </div>
  
</div>
{% endblock content %} 

story8fikri/templates/story8.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 89 Fikri</title>
{% endblock meta %}
{% block content %}
<div class="allcontent">
  <form method="GET" class="form" action="volumes">
    {% csrf_token %}
    <div class="form-group">
      {% if user.is_authenticated %}
      <label for="status" class="labelsearch"
        >Hey {{ request.user.username }}, do you wanna search some
        books?</label
      >
      {% else %}
      <label for="status" class="labelsearch"
        >Hey Anonymous, do you wanna search some books? login dulu
        please</label
      >
      {% endif %}
      <input
        type="text"
        class="form-control"
        id="searchfield"
        placeholder="search your books"
        name="searchfield"
      />
    </div>

    {% if user.is_authenticated %}
    <button type="submit" class="btn btn-primary" id="submit">Search</button>
    <a
      class="btn btn-danger"
      href="{% url 'story9fikri:SignOut' %}"
      id="text-nav-oauth"
      >Sign Out</a
    >
    {% else %}
    <a
      class="btn btn-success"
      href="{% url 'story9fikri:SignIn' %}"
      id="text-nav-oauth"
      >Sign In</a
    >
    {% endif %}
    <div id="log-button"></div>
  </form>
</div>

<div class="container mt-5">
  <h1 class="keyword-results">Results</h1>
</div>

<div id="book-results-table" class="table-responsive">
  <div class="container mt-5">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th class="align-middle" scope="col">No.</th>
          <th class="align-middle" scope="col">Book Information</th>
          <th class="align-middle" scope="col">Cover</th>
        </tr>
      </thead>
      <tbody id="results"></tbody>
    </table>
  </div>
</div>

  {% endblock content %} 

story9fikri/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 89 Fikri</title>
{% endblock meta %}

  {% block content %}
  <div class="SignIn">
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">
            
          </div>
          <div class="d-flex justify-content-center form_container">
            <form method="POST">
              {% csrf_token %}
              <div class="input-group mb-3">
                <input
                  type="text"
                  name="username"
                  class="form-control input_user"
                  value=""
                  placeholder="username"
                />
              </div>
              <div class="input-group mb-2">
                <input
                  type="password"
                  name="password"
                  class="form-control input_pass"
                  value=""
                  placeholder="password"
                />
              </div>
              <div class="d-flex justify-content-center mt-3 login_container">
                <button type="submit" name="button" class="btn login_btn">
                  Sign In
                </button>
              </div>
            </form>
          </div>
          {% if error %}
          <div class="alert alert-warning alert-dismissible fade show">
            <strong>Warning!</strong> {{ error }}
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  {% endblock content %}
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    />
    <script
      type="text/Javascript"
      src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    ></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <title>FIKRI</title>
    <nav class="nav">
      <div class="navbar-brand">Achmad Fikri Adidharma</div>
      <a class="nav-link"  href="{% url 'story7fikri:home' %}">story7</a>
      <a class="nav-link"  href="{% url 'story8fikri:book' %}">story8</a>

    </nav>


</head>
<body style="background-color: #EDF2F4;">
    {% block content%}
    
    {% endblock content%}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/ok.js' %}"></script>
    <script src="{% static 'js/story8.js' %}"></script>
  </body>
</html>